app_name = "pktdump"
main_core = 0
worker_cores = [0]

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "eth1"
    device = "net_pcap0"
    args = "rx_pcap=tcp4.pcap,tx_iface=lo"
    rx_cores = [0]
    tx_core = 0

[[ports]]
    name = "eth2"
    device = "net_pcap1"
    args = "rx_pcap=tcp6.pcap,tx_iface=lo"
    rx_cores = [0]
    tx_core = 0
